---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: ClusterIP
  selector:
    app: petclinic
  ports:
  - name: petclinic
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: admin
    port: 9090
    protocol: TCP
    targetPort: 9090


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
  annotations:
    argocd-image-updater.argoproj.io/image-list: "app1=docker.io/rajsomesetty/petclinic-pr"
    argocd-image-updater.argoproj.io/app1.update-strategy: "latest"
    argocd-image-updater.argoproj.io/app1.ignore-tags: latest, master
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/pull-policy: Always
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: workload
          image: docker.io/rajsomesetty/petclinic-pr:48-critical
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
            - name: SERVICE_BINDING_ROOT
              value: /bindings
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          volumeMounts:
            - mountPath: /bindings/secret
              name: binding
              readOnly: true
      volumes:
        - name: binding
          projected:
            sources:
              - secret:
                  name: demo-db
